version: '3'

services:
  web:
   image: nginx
   volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - .:/var/www/html
   ports:
     - '8080:80'
   restart: always
   depends_on:
     - php
     - mysql

  php:
    build:
      context: .
    restart: always
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ~/.docker/data/lumen-budget/db:/var/lib/mysql

  redis:
    image: redis:6.0-alpine
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ~/.docker/data/lumen-budget/redis:/var/lib/redis
    ports:
      - '6379:6379'

  composer:
    image: composer
    volumes:
      - .:/var/www/html
    command: install
    working_dir: /var/www/html
    depends_on:
      - php

  artisan:
    build:
      context: .
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
