name: Dime Budget API

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Storage
      run: |
        ln -sfn ${{ secrets.STORAGE_SETUP }} storage
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Update Composer
      run: composer update --lock

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Setup Env
      run: |
        cp ${{ secrets.ENV_SETUP }} $GITHUB_WORKSPACE/.env
